site_name: Trip.js
site_url: http://eragonj.github.io/Trip.js
repo_url: https://github.com/EragonJ/Trip.js

theme: yeti
pages:
  - Home: 'index.md'
  - Documentations:
    - 'Setup': 'documentations/setup.md'
    - 'Configuration': 'documentations/configuration.md'
    - 'API': 'documentations/api.md'
    - 'Theme': 'documentations/theme.md'
  - Demo: 'demo.md'
