site_name: Trip.js
site_url: http://eragonj.github.io/Trip.js
repo_url: https://github.com/EragonJ/Trip.js

theme: cosmo
extra_css:
  - vendor/trip.js/trip.min.css
extra_javascript:
  - vendor/trip.js/trip.min.js
  - js/bootup.js
  - js/demo.js
pages:
  - Home: 'index.md'
  - Documentations:
    - 'Setup': 'documentations/setup.md'
    - 'Configuration': 'documentations/configuration.md'
    - 'API': 'documentations/api.md'
    - 'Theme': 'documentations/theme.md'
  - Demo:
    - 'Basic': 'demo/basic.md'
    - 'Highly Customized': 'demo/customized.md'
